# .swiftlint.yml

# 코드 줄 길이 제한 설정 (120자까지는 경고, 160자 이상은 오류)
line_length:
  warning: 300
  error: 400

# 들여쓰기 설정
#indentation:
#  tabs: true

# 무시할 설정
disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
